
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 11;
  public static final int MENOR = 17;
  public static final int CADENA = 2;
  public static final int INT = 19;
  public static final int IGUAL = 13;
  public static final int FINCADENA = 6;
  public static final int DECIMAL = 4;
  public static final int IMPRIMIR = 7;
  public static final int TRUE = 22;
  public static final int IF = 24;
  public static final int UMENOS = 12;
  public static final int ID = 5;
  public static final int STRING = 21;
  public static final int EQUALS = 14;
  public static final int EOF = 0;
  public static final int FALSE = 23;
  public static final int error = 1;
  public static final int PAR2 = 9;
  public static final int LLAVE2 = 16;
  public static final int PAR1 = 8;
  public static final int LLAVE1 = 15;
  public static final int BOOL = 25;
  public static final int ENTERO = 3;
  public static final int FOR = 18;
  public static final int VOID = 26;
  public static final int MAS = 10;
  public static final int DOUBLE = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "ID",
  "FINCADENA",
  "IMPRIMIR",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "IGUAL",
  "EQUALS",
  "LLAVE1",
  "LLAVE2",
  "MENOR",
  "FOR",
  "INT",
  "DOUBLE",
  "STRING",
  "TRUE",
  "FALSE",
  "IF",
  "BOOL",
  "VOID"
  };
}

